### ISSUE TITLE
TLOS (Telos.Decide) appearing in token list

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-wallet#114]
## Overview
TLOS (telos.decide) appearing in token list, and "moves up and down" during regular balance refresh. Seems to happen randomly on Safari.
![image](https://user-images.githubusercontent.com/2939354/210682349-57520e3d-ea5a-4763-8011-3d2fcbb880a8.png)

## Acceptance Criteria
* TLOS (telos.decide) should be removed from the list

**Comment by donnyquixotic** [comment]
Resolved
