### ISSUE TITLE
integrate EVM interaction API from teloscan into the Antelope lib

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#204]
## Overview
The current version of the Antelope library lacks a method to interact with the Ethereum Virtual Machine (EVM) by signing transactions using Metamask. This functionality is already implemented in Teloscan, so the goal is to integrate the useful code from Teloscan into the new Antelope library.

- As a developer, I want to have a group of functions that form an API within the Antelope library. This API should allow me to interact with the EVM by signing transactions using Metamask.

## Acceptance Criteria
- The API must be cleanly implemented within the Antelope library.
- The functions must interact with the EVM and be able to sign transactions using Metamask.
- The API must allow calling any action from any contract on EVM

**Comment by donnyquixotic** [comment]
implemented
