### ISSUE TITLE
Add switch network prompt if not on telos

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#22]
add network confirmation/switch logic for metamask-related transactions
![image](https://user-images.githubusercontent.com/6848910/193959706-dba2e96f-2e02-4b21-a532-afaec1912d34.png)

**Comment by karynemayer** [comment]
@donnyquixotic @poplexity 
Could this be a future feature where we could make it easier to connect the metamask to change the chain and address?
You would be prompted to add telos EVM network if you don't have it listed and copy the EVM address to the `to EVM` field.

@Viterbo @Kersten-TCD @EJSG

**Comment by poplexity** [comment]
For now I don't think we want metamask to pop up at all, not sure why it is?

**Comment by Kersten-TCD** [comment]
I would propose to find the bug and remove it for now, still strange it would try to connect to MetaMask anyway. May be the MM screen remained active from a different or previous browser tab?

We will look at the integration to station once we focus on EVM connection.

**Comment by Viterbo** [comment]
I having some trouble to even understanding what is the bug/problem. From what I understand, the website does not interact at all with Metamask because is not needed for anything. All transactions are pushed to `eosio.evm` contract and therefore no Metamask interaction is needed.

**Comment by Kersten-TCD** [comment]
@donnyquixotic I have never investigated this behavior, can you recreate this? If not, we may want to close this issue here.

**Comment by karynemayer** [comment]
@Kersten-TCD do you know where we interact with the metamask?

**Comment by Kersten-TCD** [comment]
Not (yet) anywhere within the web-wallet or OBE, this is only supported for Teloscan and will be for Telos Station going forward.

**Comment by donnyquixotic** [comment]
Resolved
