### ISSUE TITLE
incorporate staking management code from teloscan into the new store library

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#222]
## Overview
In order to implement staking in the new Telos wallet for EVM, we need to incorporate the staking management code from Teloscan. This code currently solves the staking problem on the Teloscan site and can be used to provide a similar solution in the new wallet.

## Acceptance Criteria
- The code must be sourced from Teloscan.
- The code must solve _staking_, _unstaking_, and _withdrawal_.
- The code must automatically obtain the balance of the involved tokens (sTLOS and TLOS) by detecting changes in the authenticated account.
- The solution should primarily be implemented in the `rex` store.

## Technical notes
Those methods contain most of the effort:
https://github.com/telosnetwork/teloscan/blob/dev/src/pages/staking/Staking.vue#L63-L249

**Comment by donnyquixotic** [comment]
Implemented
