### ISSUE TITLE
As a user I want the site to respond to me swapping my account directly on the wallet.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#226]
## Overview
As a user I want the site to respond to me swapping my account directly on the wallet.

Users can directly interact with their wallets and select an active account, the site should respond by detecting this event and swapping to the active account and displaying the data for it.
## Acceptance Criteria
User connects to multiple accounts using the wallet, A and B. A is the active account and the wallet display A's information,
the user then swaps active account to B and the site responds by loading and displaying the information for B and making it the active account for all actions.

**Comment by donnyquixotic** [comment]
Resolved
