### ISSUE TITLE
Style | we need to define the colors for menu-items hover 

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#228]
![image](https://user-images.githubusercontent.com/4420760/230153042-eb6a7cb2-99db-491c-b0de-4f1c722c8b3c.png)

**Comment by karynemayer** [comment]
Please, check [here](https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?node-id=123%3A453&t=tgy0ImjtjlKMAtI0-1).

@pmjanus any feedback on the design?
