### ISSUE TITLE
Price Source for Wallet -> Spike

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-wallet#241]
## Overview
We need to include some endpoints to acquire FIAT values.

## Acceptance criteria
- Have a trusty endpoint for TLOS
- Include up to 5 other tokens that are the most common

## Time
3 hours

Result:
Expect to have an endpoint on Teloscan where you send a contract address and a currency list and you get back the latest price for those currencies, initially only USD supported. For TLOS you will use WTELOS contract address.

**Comment by pmjanus** [comment]
We will use Teloscan API to receive price data for system token, ERC20s and NFTs as it gets implemented.
