### ISSUE TITLE
Balance Accuracy

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#25]
- [ ] Token balance (wallet) / REX staking balance (unstake) not accurate compared to EOS-Authority, please check with @WikusKriek we have been working on this for OBE, too

**Comment by karynemayer** [comment]
@donnyquixotic @WikusKriek  I'm under the impression you already fixed this, but I'm not sure of which bug on OBE this refers to. Could you add the bug reference and perhaps update the description?

**Comment by karynemayer** [comment]
Duplicate from https://github.com/telosnetwork/telos-wallet/issues/46
