### ISSUE TITLE
Refactoring - find a better place for the new notification component

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#254]
## Description
The current implementation of the new notification system is not placed appropriately. We need to find a better place for the component implementation.

The "component" is not a normal component since is a plain HTML text used in the call for Quasar notify functionality, which only admits customizing the internal HTML through a plane string property `message:"html-string"` and enabling the HTML recognition with a flag `html:true`. However, using classes and EBM styling practices the current implementation fits the expected aspect.

**Comment by donnyquixotic** [comment]
@Viterbo is this still relevant? If not, please close.

**Comment by Viterbo** [comment]
It already has a good place
