### ISSUE TITLE
Refactoring | Centralized text styling

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-wallet#259]
## Overview
Right now, we're styling every text individually in the new components. This makes keeping the text styling consistent throughout the application nearly impossible. Also, this is the right time to do it:
- We already have the styles defined with Figma
- We don't have tons of pages to review that have been developed

### Currently used styles
The styles that are being used in the design are the following. The current naming is a copy of what has been used so far, but the team should have full authority over it.

Some styles should be assumed unless specified otherwise:
```css
font-style: normal;
line-height: 150%;
font-family: 'Silka', 'Roboto', sans-serif;
text-align: left;
```

#### h1
Used exclusively for the current user balance and page titles (e.g. send, receive).

```css
font-weight: 600;
font-size: 40px;
line-height: 48px;
```

#### h2
```css
font-weight: 600;
font-size: 24px;
line-height: 130%
```

#### h3
```css
font-weight: 400;
font-size: 24px;
line-height: 130%
```

#### h4
```css
font-weight: 400;
font-size: 20px;
line-height: 130%
```

#### h4 for mobile (< 600px width)
```css
font-weight: 400;
font-size: 18px;
line-height: 130%
```

#### p
```css
font-weight: 400;
font-size: 16px;
line-height: 150%
```

#### p-bold
```css
font-weight: 600;
font-size: 16px;
line-height: 150%
```

#### label
Generally used as a label, on buttons and for USD values

```css
font-weight: 600;
font-size: 14px;
line-height: 150%
text-transform: uppercase;
```

#### small
```css
font-weight: 600;
font-size: 12px;
line-height: 150%
```

#### small-bold
```css
font-weight: 600;
font-size: 12px;
line-height: 150%
```

**Comment by Viterbo** [comment]
@karynemayer, we also need to solve the style of the buttons which currently suffers from the same problem.

Here is [your feedback](https://github.com/telosnetwork/telos-wallet/pull/266/files/92a410f79996943af80f18eb17bffb13660bef38#r1175840112) about it.
