### ISSUE TITLE
NFT navigation

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#26]
- [x] Click on "NFT" in navigation does not activate "collectables" tab, except when wallet modal is opened, try to open from

**Comment by donnyquixotic** [comment]
@Kersten-TCD can you add reproduction steps or we can walk through it.

**Comment by Kersten-TCD** [comment]
Steps to reproduce:

- login to web-wallet
- Click on "wallet" and open the "wallet" page
- Then click on "NFT", this will activate the "Collectable" tab on the "wallet" page
- Now click on "Profile" or "dApps" and open the page
- Click on "NFT" again, this will open the "wallet" page but does not activate the  "Collectable" tab
