### ISSUE TITLE
Refactoring | find appropiate name for the current global store

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#271]
## Description
Currently, we have two types of stores. One is built using the Vuex library, which only covers some parts of the native wallet, while the other is a new store built using the Pinia library. Although the Pinia store is growing, it currently only has a single data point.

Before proceeding with the migration of the old Vuex stores to the new Pinia store, we need to better define the names and structure of the new storage system.

This global store was renamed to `appnav` because it suits better the current usage of it. This change is made in [this branch](https://github.com/telosnetwork/telos-wallet/blob/223-send-page-api-integration-incorporate-support-for-sending-evm-tokens/src/stores/appnav.ts) which is part of [this PR](https://github.com/telosnetwork/telos-wallet/pull/257)

## Consider
- Remove the store entirely

**Comment by EJSG** [comment]
Closing as this will be addressed as a part of #347
