### ISSUE TITLE
Refactoring - change current receive & send pages to modals

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#272]
## Update
Solution is in place, only item missing from proposed is the exit animation

## Description
Currently the receive and send pages are very dependent on the navigation structure that @EJSG's designed. Therefore, they behave like a page (which replaces the current content to place new content) and not like a dialog (which supposes new content on top of the existing one, being able to add animations of entering and leaving the scene).

Since the requirement to be a dialog came late (we already had a finished version of the page), an attempt was made to emulate the behavior of a modal by hiding the header and presenting the new content with an entry animation. However, this simulation would not be enough since we do not have an exit animation.

## Acceptance Criteria
The final solution should behave as if it were a modal, having an enter animation, an exit animation and completely covering the header to present its own back button.

Two options are proposed:
- implement real dialogs
- implement an exit animation that simulates exiting the dialog

**Comment by donnyquixotic** [comment]
Solution is already in place including full coverage of header, back button and entry animation, only enhancement missing is the _exit_ animation.
