### ISSUE TITLE
Account creation error (native)

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#314]
**Describe the bug**
If user doesn't have enough RAM to generate an EVM address, account creation fails.

**To Reproduce**
1. Log into wallet.telos.net (native) with account that does not have an EVM address and maxed out RAM useage
2. Click generate evm address
3. See error

**Expected behavior**
Should generate EVM address

**Screenshots**
![image](https://github.com/telosnetwork/telos-wallet/assets/6848910/3844d8b7-7a67-47d4-b1a0-5f6b8e092d26)

**Additional context**
Fuel may be adding actions that the UI is rejecting

**Comment by pmjanus** [comment]
We want to inform those using this Native EVM address

That the address that’s generated to use with your native/anchor account… nobody has that private key
So we need to discourage and make it clear to never use that address elsewhere
People have tried to use it on other networks and locked assets in it
