### ISSUE TITLE
Argent Wallet and WalletConnect Connection Doesn't Work on Android

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#398]
**Describe the bug**
Trying to connect with wallet connect on android chrome shows a weird modal (see  1st screenshot below)

**To Reproduce**
1. Download metamask app on android
2. download argent app on android
3. go to staging branch on android and try to login using wallet connect
4. you see 1st screenshot instead of metamask wallet and argent wallet
5. hitting connect leads you to argent wallet
6. my argent wallet doesnt have telos evm networks and on argent there is no indication you are connected or you are trying to connect to the wallet
7. flow ends at argent, if you go back to chrome telos evm staging you are still at screenshot #1 view

**Expected behavior**
I expect the wallet connect modal to include wallets I can choose, I choose metamask and it works or I choose argent and it works
if I am on the wrong network I expect to receive a message on wallet that says I need to connect to the correct network.

**Screenshots**
![telegram-cloud-photo-size-1-5186233629544655741-y](https://github.com/telosnetwork/telos-wallet/assets/97489909/01c56115-8960-4e0a-95a3-45a06c4f7c1e)

**Smartphone (please complete the following information):**
 - Android chrome

**Comment by ezra-guzman** [comment]
not happening anymore, closing
