### ISSUE TITLE
Transactions not shown on UI

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-wallet#423]
**Describe the bug**

When logging into the wallet on my **0xe7209d65c5BB05Ddf799b20fF0EC09E691FC3f11** account and clicking on the `transactions` tab, the transactions for my account load but do not show up in the UI:

![image](https://github.com/telosnetwork/telos-wallet/assets/5913758/27479fa7-7688-454b-9c19-d4f193fa182c)
![image](https://github.com/telosnetwork/telos-wallet/assets/5913758/09284527-5c59-40e2-9988-21ec2737124f)

Then if I click next page it tries to query with offset -5 and fails:

![image](https://github.com/telosnetwork/telos-wallet/assets/5913758/f2eb5474-3aee-4ec1-bded-8b5e6ffc47e9)

**To Reproduce**
Hard to give reproduce-able steps as this depends on the account

**Expected behavior**
I should be able to see my transactions and traverse them.

**Screenshots**
See description

**Desktop:**
 - OS: Window
 - Browsers: Brave, Chrome
 - Versions: Chrome 113.0.5672.127 64bit, Brave 1.52.126 (Chromium: 114.0.5735.133) 64bit

**Comment by pmjanus** [comment]
Fixed on develop version, can test by hardcoding the address shared 0xe7209d65c5BB05Ddf799b20fF0EC09E691FC3f11 
 on src/antelope/chains/EVMChainSettings.ts line 199 and checking out the transactions tab.

**Comment by donnyquixotic** [comment]
Resolved
