### ISSUE TITLE
EVM Wallet - Tx refresh UX/UI 

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#434]
Discussing with the team we realized there are improvements to be made once you are in the tx tab and you want to be informed of new transactions or you want to refresh the page or it to be auto refreshed to get new transactions.
Let's use this issue to brainstorm solutions and improve UX and UI on this page.

**Comment by donnyquixotic** [comment]
closing this as resolved as transactions are automatically updated now
