### ISSUE TITLE
Cannot: Using WalletConnect Metamask QR code to connect from ANDROID Metamask application

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#488]
**Describe the bug**
Using WalletConnect Metamask QR code to connect from ANDROID Metamask application does not work. The code does not get scanned. It DOES work on iOS but it seems to direct you to the TelosEVM testnet.

**To Reproduce**
1. Open wallet.telos.net click wallet connect
2. scan with metamask qr scanner on android or ios
3. on android nothing happens most of the time, when the qr view closes, no connection happens
4. on ios qr connects and you are swapped to telos evm testnet

**Expected behavior**
1. qr scanning on ios works on correct network
2. qr scanning on android works on correct network

**Comment by donnyquixotic** [comment]
resolved, tested on both Android and ios
