### ISSUE TITLE
Restoring Ore ID Login Button

### ISSUE THREAD

**Issue by ezra-guzman** [telosnetwork/telos-wallet#492]
Blocked: awaiting OreID team to reach out

In env.js, the ore ID application ID needs to be updated

**Comment by Viterbo** [comment]
I went to https://oreid.io/developer and created my own account as a developer and then I created a new App to connect using the service. As a free-to-try service, it only allows me to set one blockchain associated with my app and it is always testnet.
Finally, I got to the configuration panel where I can select the OAuth Providers that I want to support in my app. 
Also, I needed to add some url to be supported and I added the [deploy netlify link](https://deploy-preview-490--wallet-staging.netlify.app/) to be able to test it from the PR's deploy. Those changes were easy for me to test if I'm the admin for the app registration. Now that everything is tested and works, we can proceed with the actual App ip, which is something @pmjanus is doing.

![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/c6d22343-6753-4fd0-b245-e2aac3c784b5)
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/2b636793-0a26-4b14-ba1c-f1ab4664ce31)
