### ISSUE TITLE
ERC1155 Inventory/detail page updates

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/telos-wallet#499]
## Overview
As a user, I should be able to see basic information pertaining to my ERC1155 tokens in the Inventory and NFT Detail pages

## Acceptance Criteria
**Inventory page**
- in tile view, a badge should be added to the bottom left corner of each NFT which the user has more than 1 of
    - the badge should truncate after 4 numerical characters (e.g. display x9,999 and then x10k)
    - on hover of the badge, a tooltip should be displayed showing the exact number of that NFT in the user's inventory (full number should be displayed in a localized way)
- in list view, a new column `Quantity` should be displayed
    - there should be no truncation of the number
    - number should be formatted in a localized way
design: https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?type=design&node-id=1410-8426&mode=design&t=9OZ9WzqKrrDLFu4x-4
- Test transfer, see #448 

**Detail page**
- for ERC1155 NFTs only, there should be 2 new boxes in the header section "Owned" and "Total" representing the total number of existing NFTs of that type, and how many the user owns
- https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?type=design&node-id=1450-9022&mode=design&t=9OZ9WzqKrrDLFu4x-4

**Misc**
- loading state (skeleton) for the NFT inventory page should be updated to fix the horizontal alignment with other elements on the page

**Comment by ezra-guzman** [comment]
@tomtomcrypto we are not getting a result for 1155 token, can you confirm the state of the indexer?
https://api.teloscan.io/v1/contract/0x78cb091062cc8c32CD9c814599d1987b1dCc5093/nfts?limit=50&offset=0&sort=0&includePagination=false&includeAbi=false

**Comment by pmjanus** [comment]
@ezra-guzman We can get results now, Tom updated the indexer api. Can you verify if this is still blocked if not move it to ready to start?

**Comment by ezra-guzman** [comment]
> @ezra-guzman We can get results now, Tom updated the indexer api. Can you verify if this is still blocked if not move it to ready to start?

nice, it is working
