### ISSUE TITLE
Fix profile image responsiveness

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#50]
**Description**
Inconsistent responsive spacing for profile image results in it being cut off between full-screen and mobile hidden breakpoint. 

**Solution**
The profile image container should be consistently spaced relative to the edge of the browser window until mobile breakpoint.

**Screenshot**
![image](https://user-images.githubusercontent.com/6848910/200093805-1ef26b98-00f8-4d82-afdc-6cfe60d87d20.png)
![image](https://user-images.githubusercontent.com/6848910/200093833-746e6b77-caaf-4d1d-9d25-73cc44ab05bb.png)
![image](https://user-images.githubusercontent.com/6848910/200093845-9989d133-a432-4c0c-9fb7-a9f83b0f2134.png)

**Comment by Viterbo** [comment]
This issue was solved at https://github.com/telosnetwork/telos-wallet/pull/72
