### ISSUE TITLE
localization missing for network_switch_success

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#514]
**Describe the bug**
An entry on the localization strings is missing

**To Reproduce**
1. Set a non-telos-testnet network on your MetaMask 
2. Try to login with MetaMask
3. when prompted, switch network
4. A sign with no translation will appear (see screenshot)

**Screenshots**
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/18b198e6-8178-429c-84a3-3432c476ad71)

**Comment by donnyquixotic** [comment]
@Viterbo closing this as duplicate (see #508), copied over the screenshot.
