### ISSUE TITLE
[SPIKE] Look into e2e testing (cypress)

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/telos-wallet#529]
It would be great if we had selenium end-to-end/integration testing as a part of our CI/CD flow to reduce the manual testing time required. However we do not know how long it would take to implement this, and if the time savings would ultimately be worthwhile. This tech spike is aimed at understanding what it would take to implement selenium testing into web wallet (and in the future, other projects). 

Time 8 hours. 
deliverables:
- analysis of the usefulness of implementing headless browser testing, including its limitations
- wallet testing, approaches and libraries we could use, the plan should have a section on this
- analysis of how AI can help streamline the process
- time estimate, perhaps a generalized formula for understanding feature complexity to testing complexity
- a general plan of action for adding in this testing, should we choose to move forward with it
- implement a simple test in a feature branch

@donnyquixotic  notes:

Cypress
- chrom[ium] support for quasar app extension (?)
- https://docs.cypress.io/guides/tooling/typescript-support#Clashing-types-with-Jest (override globals)
- redudnant unit testing support via components lib
- requires additional attributes for targeted elements (recommended)
- can run headless for CI with video capture output
- coverage reporting not available for webpack (available for vite)
- v10 issues
- straightforward testing

Synpress
- MetaMask e2e support as a cypress plugin
- No explicit vue support but [should still work](https://github.com/Synthetixio/synpress/issues/164) (built for react)
- standalone option 
- not recommended to run headless for CI

Other MM cypress e2e links:
- https://www.npmjs.com/package/cypress-metamask-v2
- https://github.com/CraftAcademyLabs/cypress-metamask
- https://medium.com/coinmonks/test-e2e-login-to-dapp-with-metamask-with-synpress-5248dd1f17c1

- mobile support?
- window/tab/popup navigation
- other wallet options/cloud wallet

**Comment by duckception** [comment]
Hey Telos team! 👋

I'm one of the core devs behind Synpress, and I just noticed you've considered using our tool for E2E testing. 

Since you're in the middle of the spike, If you have any questions or doubts regarding testing using your wallet or MetaMask, utilizing Synpress, Cypress, or Playwright libraries, or have other general questions about E2E testing in the Web3 world, I'd be down to chat and shed some light on this topic (no matter which tool you're going to end up using).
