### ISSUE TITLE
Add timeout to loading state for actions

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/telos-wallet#543]
Presently, on pages which allow the user to create transactions (wrap, unwrap, send, login), there is a loading state while we await the user's input. when something unexpected occurs, such as the metamask app never popping a transaction confirmation dialog, the user gets stuck in a permanent loading state. we should have a solution to end the loading state after some amount of time, perhaps 15 seconds. we should also show a notification to the user in these scenarios indicating that a timeout occurred.

**Comment by donnyquixotic** [comment]
resolved, loading states are canceled for all current actions on user rejection, it only persists if user ignores MetaMask prompt in which case it is queued and can be dismissed by refreshing page, which is fine.
