### ISSUE TITLE
Self transfers not showing the receipt of the ERC20

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#558]
**Describe the bug**
I sent the same address I was connected with 10 USDT and when I looked at the transactions tab only the -10 USDT appeard.
It should be -10 and +10.
https://www.teloscan.io/tx/0x424733ae19e3c1e5c29df8f4ed0e5dee64119209ea1cd002d9c597d074b9fedf 

**To Reproduce**
connect with wallet, send self ERC20 and look at tx tab, check to see if it happens with tlos as well

**Expected behavior**
Tx shows sending and receiving, imo would be more informative than  just the net change (0USDT).

**Screenshots**
<img width="618" alt="image" src="https://github.com/telosnetwork/telos-wallet/assets/97489909/a950ccd0-d973-4b41-ab0f-e821a5725d7d">

**Comment by donnyquixotic** [comment]
resolved
