### ISSUE TITLE
Unified notifications handling

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#57]
## Overview

The goal of this issue is to improve the overall code quality. On telos-wallet, we have different ways to handle errors, as seen below:

https://github.com/telosnetwork/telos-wallet/blob/84b2a0e14342ed6f692e5fb98211e8cd5952f31e/src/boot/errorHandling.js#L4-L21

https://github.com/telosnetwork/telos-wallet/blob/84b2a0e14342ed6f692e5fb98211e8cd5952f31e/src/pages/components/balance/Exchange.vue#L508-L511

Then, this would either call `errorNotification` or another function would be created if the different treatment makes sense. Either way, all error and warning handling should be directed to the same file.

## Acceptance criteria

- All error and warning handling should go to the `errorHandling.ts` file
- If any other visual is required, it should be included in the file as another functions
- No `$q.notify` should be used directly for errors

**Comment by Viterbo** [comment]
This issue was originally created in the [app-telos-native repo](https://github.com/telosnetwork/app-telos-native) and later migrated to this repo. But the thing is that it does not apply here because the notification process is handled in a different way.

In app-telos-native we have a centralized solution for notification and it uses a _status_ (which currently is a string and should be an Enum) to set the modal colors and icons.

https://github.com/telosnetwork/app-telos-native/blob/b05f258546044e983bdfccab32b768298ff4fc34/src/store/tokens/actions.js#L106-L110

https://github.com/telosnetwork/app-telos-native/blob/b05f258546044e983bdfccab32b768298ff4fc34/src/App.vue#L18

But the telos-wallet has a different approach. It has a single point to handle and show any error.

https://github.com/telosnetwork/telos-wallet/blob/master/src/boot/errorHandling.js#L4-L21

and is used like this

https://github.com/telosnetwork/telos-wallet/blob/master/src/components/LoginButton.vue#L279-L281

And the normal message is handled using the native quasar `notify()` service like this:

https://github.com/telosnetwork/telos-wallet/blob/master/src/pages/components/balance/Exchange.vue#L508-L511

This issue needs more grooming

**Comment by karynemayer** [comment]
@Viterbo @donnyquixotic would make sure every error on web-wallet uses `errorNotification` be a more coherent acceptance criteria for this project?

https://github.com/telosnetwork/telos-wallet/blob/84b2a0e14342ed6f692e5fb98211e8cd5952f31e/src/boot/errorHandling.js#L4-L21

Then, this would either call `errorNotification` or another function would be created if the different treatment makes sense.

https://github.com/telosnetwork/telos-wallet/blob/84b2a0e14342ed6f692e5fb98211e8cd5952f31e/src/pages/components/balance/Exchange.vue#L508-L511
