### ISSUE TITLE
Change cancel icon notification type

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#573]
<img width="556" alt="image" src="https://github.com/telosnetwork/telos-wallet/assets/97489909/2da9ebc9-703d-4c63-937c-6c53a6c16077">
Should be informative, and no OOPS, if the user canceled.  Let's just throw, You cancelled the action. We should include info on the action if we have it.

**Comment by Viterbo** [comment]
I reopen this issue because keeps showing the old red "Error" notification when using OreIdAuth.
If you close the popup it shows the Error notification
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/efbbac91-1d32-4a10-ba00-2f699349707f)
