### ISSUE TITLE
[SPIKE] Research error logging systems like Sentry.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#578]
We want more information on certain errors, for example, why did a walletconnect login fail?
SENTRY could help us do that, some other software might.

Acceptance Criteria
1. Spend 2 hours researching logging and write a gpt-4 assisted report on logging options that could help us solve the problem above.
2. Plan a KT to talk about this 20 mins with ze Team.

**Comment by ezra-sg** [comment]
Findings:
It would be very useful to have the error logging provided by Sentry. It includes a log of actions taken and requests made leading up to the actual error. This would allow us to diagnose and potentially fix errors that users are seeing but not reporting. I explored several other options, but determined that they are too expensive. Integrating Sentry into the application is very easy, particularly if we use their SaaS version. However, there is a $29 monthly fee for this service. It is possible to run a self-hosted Sentry server, as it is open source and free to use, but this comes with its own overhead of 1. operational costs in terms of server memory and hard disk space, 2. setup is nontrivially difficult, with a significant amount of configuration required to get it running and accessible to production, 3. it would require regular attention to maintain the installation on the server to ensure it is always up to date (as security flaws may be present, as with any externally-facing server). Ultimately, I would recommend paying for the SaaS version, but this has the drawback of a monthly cost, which may or may not be financially feasible. The cost is also 10% lower if we pay for a yearly subscription, clocking in at $312 / yr.
