### ISSUE TITLE
Sporadic situation that throws a lot of errors in the console during the balance update process.

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#589]
**Describe the bug**
I was experimenting with a weird error that was being thrown to the console occasionally during the balance update process. I spent some time chasing that problem and although I couldn't fix it I reached to some conclusions.

What I know about that bug:
- only happens when logged with WalletConnect or OreID
- happens during updating balances (sometimes, not always)
- is somehow related to the use of JsonRpcProvider to query the balances for erc20 tokens
- is not a blocker but fills the console with errors
- It happens in develop branch too

I have stopped trying for a while and now I'm trying to get a screenshot of the console errors and I can't reproduce the %#@ bug :angry:

I will leave this issue open for a while and wait until I face the problem again so I can take a screenshot and complete the diagnosis.

**To Reproduce**
Currently, I'm not being able to reproduce that bug.

**Comment by donnyquixotic** [comment]
@Viterbo Is this still an issue that you're aware of? Feel free to close if you cannot reproduce.
