### ISSUE TITLE
Refactoring effort

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-wallet#67]
## Overview

This task aims to identify what needs to be refactored in the code base for us to consider it quality code. 

## Acceptance criteria

- Identify the changes we want to address 
- Scope what good quality code is

**Comment by karynemayer** [comment]
@donnyquixotic could you update the acceptance criteria and the list of issues resulting from this?

**Comment by poplexity** [comment]
To define "quality code" is a very arbitrary thing.  I am sure there are aspects of the code which we'd all agree are not quality, and there is generally a lot of complex and poor implementation things that we can clean up.  We can probably remove a lot of code that's not used and clean up how a lot of it is written so it's simpler.  I think we could also modify this issue to just define what to clean up, and then track the actual cleanup work in other issues.

**Comment by Viterbo** [comment]
@poplexity, If you agree I can take a deep look in search for those not-so-good code solutions that way deserve a refactor. I will write them down as separate potential issues.

Later, we can have a discussion over a well-defined list of tasks and assign them the corresponding priorities and planning.

**Comment by Viterbo** [comment]
To accomplish the second acceptance criteria of "Scope what good quality code is" I'm writing down the following criteria that I will follow to identify potential refactor targets in the current code:

## What would be a list of good practices for a Vue + Quasar app?
- Use the Vuex library for managing your application's state.
- Components should be as reusable as possible.
- Components should be the most isolated possible.
- When the component is very specific, it should interact directly with the corresponding `vuex.Store`
- All components' specific style should be in the file with `global` scope and written in `scss` applying BEM standard
- In general, the code should be as simple-to-read as possible
  - naming properly
  - commenting on complex blocks of code
  - reduce complexity as much as possible

**Comment by karynemayer** [comment]
@poplexity @donnyquixotic What do you think?
