### ISSUE TITLE
Include netlify/cloudfare integration to PRs

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-wallet#73]
## Overview

Telos wallet does not provide temporary urls where the PR code is deployed. Since this project is to become one of the main projects for telos, those deployments become even more crucial for testing and quality assurance.

## Acceptance criteria

- When opening a new PR, a url is generated with the code of the PR

**Comment by Viterbo** [comment]
This taks has already done by @donnyquixotic So I close this issue
