### ISSUE TITLE
Wallet UI updates

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/telos-wallet#735]
There are some low hanging objectives we can address to make the UI/UX on wallet better

- [x] 1. the Brave wallet login option should appear below the others, and walletconnect should be second after metamask
- [x] 2. we should add analytics for brave login so we know how many people use it
- [x] 3. the login menu should not jump around when switching between tEVM and Zero on the home page
- [x] 4. the buttons should be consistently styled between tEVM and Zero buttons, including hover styling  
- [x] 5. terms of service link in the footer is broken - it should match telos.net
- [x] 6. buy link on evm wallet doesnt work, it should link to https://telos.net/ecosystem?category=Exchanges
- [x] 7. NFTs link on evm wallet left nav should be below staking; staking should be second
- [x] 8. there should be a teloscan link below the ecosystem link in the evm wallet left nav. overflow menu on the top right can be removed, as it is redundant
- [x] 9. show "More info" link instead of "trx: 0x....." for transactions in the evm wallet
- [x] 10. when disconnecting on telos zero wallet, use should be returned to the home page with Zero login tab selected
- [x] 11. telos zero purchase link is broken, see point # 7
- [ ] 12. remove tswaps link in zero wallet > "Convert"
- [x] 13. remove areax from dapps page on zero wallet

**Comment by donnyquixotic** [comment]
related #737
