### ISSUE TITLE
Autologin issue when wrong network selected

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/telos-wallet#779]
The application gets into a weird state if the user loads the app with an incorrect network selected (e.g. Ethereum mainnet), visits an NFT detail page (e.g. [this one](https://wallet.telos.net/evm/collectible-details?contract=0x63F8948c2Ee0670758A4E60EED80aAa6Cf093356&id=1141&tab=attributes)), then navigates to another page without selecting the Telos network. 

## Acceptance Criteria 
We should either allow users to navigate the site normally when using the wrong network (from the NFT detail page), or if this is not possible, gate the application and prompt the user to switch networks

The video shows a PR branch, but it happens on master as well

https://github.com/telosnetwork/telos-wallet/assets/11837820/de88c858-b3ef-4a0e-b8ec-d698c44d555e

**Comment by rozzaswap** [comment]
@Viterbo to share some thoughts on a bugfix + create a second issue
