### ISSUE TITLE
Erratic behavior on Telos Zero

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#815]
**Describe the bug**
Some parts of the code are failing, throwing a "not a function" error which may cause subsequent other errors, leading to an erratic behavior.

**To Reproduce**
1. Go to https://wallet.telos.net/?login=zero
2. open console dev-tools (F12)
3. See console errors: **TypeError: t.getStakedSystemToken is not a function**

**Expected behavior**
There should be no errors on the console (other than the external lib errors).

[FIXED HERE](https://github.com/telosnetwork/telos-wallet/pull/821)

**Screenshots**
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/b18faf11-0775-45a6-9624-e34e43610b73)

**Comment by rozzaswap** [comment]
Merged to dev, good job!
