### ISSUE TITLE
handling undefined paths is broken

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#91]
# Description
The site should handle all possible paths and redirect those that are undefined, and therefore not expected, to a generic error 404 page.

## how to reproduce
1 - go to [https://wallet.telos.net/foo](https://wallet.telos.net/foo)
2 - the site shows a blank page

![image](https://user-images.githubusercontent.com/4420760/209008395-0500a232-26e4-4159-ab9c-d281c45b8958.png)

**Comment by donnyquixotic** [comment]
resolved
